### ISSUE TITLE
Can i contact you ?

### ISSUE THREAD

**Issue by Kakoum** [anonymousthing/audio-visualizer#1]
Hey @anonymousthing sorry for posting here, but i want to contact you please :( you have a adress mail ? Is about your audio visualizer and Listen.moe
 (or by DM twitter maybe).

Thanks !
My e-mail : mora.guillaumek @ gmail.com

PS : i feel bad to create a issue just for that ! :'(

**Comment by bitnimble** [comment]
I've sent you an email.
